{
 "title": "http-server-projeto-korp Dashboard",
 "tags": [
  "korp",
  "http-server"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Disponibilidade do Serviço (http_server_up)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "http_server_up" }
   ]
  },
  {
   "title": "Volume Total de Requisições",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "sum(http_requests_total)" }
   ]
  },
  {
   "title": "Taxa de Requisições por Segundo (Req/s)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by (path, method, status)",
     "legendFormat": "{{method}} {{path}} (Status: {{status}})"
    }
   ]
  }
 ]
}